import type { Customer } from "@/types";

export const mockCustomers: Customer[] = [
  {
    id: "cust-001",
    name: "Urban Denim Co.",
    location: "New York, USA",
    contactPerson: "Michael Carter",
    email: "michael@urbandenim.com",
    phone: "+1 212 555 0148",
    activeOrders: 3,
    totalOrders: 21,
  },
  {
    id: "cust-002",
    name: "Bluewash Apparel",
    location: "Manchester, UK",
    contactPerson: "Emma Whitfield",
    email: "emma@bluewashapparel.co.uk",
    phone: "+44 161 555 0192",
    activeOrders: 2,
    totalOrders: 14,
  },
  {
    id: "cust-003",
    name: "Northline Trading",
    location: "Hamburg, Germany",
    contactPerson: "Lukas Fischer",
    email: "lukas@northlinetrading.de",
    phone: "+49 40 555 0173",
    activeOrders: 4,
    totalOrders: 33,
  },
  {
    id: "cust-004",
    name: "Studio Fit Co.",
    location: "Toronto, Canada",
    contactPerson: "Sarah Nguyen",
    email: "sarah@studiofitco.ca",
    phone: "+1 416 555 0121",
    activeOrders: 1,
    totalOrders: 9,
  },
  {
    id: "cust-005",
    name: "Westgate Garments",
    location: "Sydney, Australia",
    contactPerson: "James O'Connor",
    email: "james@westgategarments.com.au",
    phone: "+61 2 5550 0187",
    activeOrders: 2,
    totalOrders: 17,
  },
  {
    id: "cust-006",
    name: "Meridian Clothing",
    location: "Dubai, UAE",
    contactPerson: "Fatima Al-Sayed",
    email: "fatima@meridianclothing.ae",
    phone: "+971 4 555 0164",
    activeOrders: 1,
    totalOrders: 6,
  },
];
