import type { Customer } from "@/types";

export const mockCustomers: Customer[] = [
  {
    id: "cust-001",
    code: "CUST-001",
    name: "Urban Denim Co.",
    type: "brand",
    location: "New York, USA",
    address: "412 Bowery Street",
    city: "New York",
    country: "USA",
    contactPerson: "Michael Carter",
    email: "michael@urbandenim.com",
    phone: "+1 212 555 0148",
    status: "active",
    notes: "Prefers stretch denim across all core styles.",
    activeOrders: 3,
    totalOrders: 21,
  },
  {
    id: "cust-002",
    code: "CUST-002",
    name: "Bluewash Apparel",
    type: "wholesaler",
    location: "Manchester, UK",
    address: "22 Cotton Exchange Way",
    city: "Manchester",
    country: "UK",
    contactPerson: "Emma Whitfield",
    email: "emma@bluewashapparel.co.uk",
    phone: "+44 161 555 0192",
    status: "active",
    notes: "",
    activeOrders: 2,
    totalOrders: 14,
  },
  {
    id: "cust-003",
    code: "CUST-003",
    name: "Northline Trading",
    type: "retailer",
    location: "Hamburg, Germany",
    address: "18 Hafen Strasse",
    city: "Hamburg",
    country: "Germany",
    contactPerson: "Lukas Fischer",
    email: "lukas@northlinetrading.de",
    phone: "+49 40 555 0173",
    status: "active",
    notes: "Largest volume account — priority scheduling.",
    activeOrders: 4,
    totalOrders: 33,
  },
  {
    id: "cust-004",
    code: "CUST-004",
    name: "Studio Fit Co.",
    type: "brand",
    location: "Toronto, Canada",
    address: "77 King Street West",
    city: "Toronto",
    country: "Canada",
    contactPerson: "Sarah Nguyen",
    email: "sarah@studiofitco.ca",
    phone: "+1 416 555 0121",
    status: "active",
    notes: "",
    activeOrders: 1,
    totalOrders: 9,
  },
  {
    id: "cust-005",
    code: "CUST-005",
    name: "Westgate Garments",
    type: "wholesaler",
    location: "Sydney, Australia",
    address: "5 Harbour Road",
    city: "Sydney",
    country: "Australia",
    contactPerson: "James O'Connor",
    email: "james@westgategarments.com.au",
    phone: "+61 2 5550 0187",
    status: "active",
    notes: "",
    activeOrders: 2,
    totalOrders: 17,
  },
  {
    id: "cust-006",
    code: "CUST-006",
    name: "Meridian Clothing",
    type: "retailer",
    location: "Dubai, UAE",
    address: "Al Quoz Industrial Area 3",
    city: "Dubai",
    country: "UAE",
    contactPerson: "Fatima Al-Sayed",
    email: "fatima@meridianclothing.ae",
    phone: "+971 4 555 0164",
    status: "inactive",
    notes: "On hold pending new season contract renewal.",
    activeOrders: 1,
    totalOrders: 6,
  },
];
