import type { GoodsReceipt } from "@/types";

export const mockGoodsReceipts: GoodsReceipt[] = [
  {
    id: "grn-001",
    grnNumber: "GRN-2026-0088",
    poId: "po-001",
    poNumber: "PO-2026-0311",
    supplierId: "sup-001",
    supplierName: "Metro Trims Supply",
    receivedDate: "2026-08-12",
    receivedBy: "Ramesh Kumar",
    items: [
      {
        id: "grn-001-item-1",
        poItemId: "po-001-item-1",
        materialId: "mat-005",
        materialCode: "ACC-ZIP-YKK",
        materialName: "YKK Zipper 5.5in",
        receivedQuantity: 10000,
        acceptedQuantity: 10000,
        rejectedQuantity: 0,
        unit: "PCS",
        inspectionStatus: "accepted",
        warehouseId: "wh-001",
        locationId: "loc-002",
      },
      {
        id: "grn-001-item-2",
        poItemId: "po-001-item-2",
        materialId: "mat-006",
        materialCode: "ACC-BTN-JN",
        materialName: "Jean Button 17mm",
        receivedQuantity: 15000,
        acceptedQuantity: 15000,
        rejectedQuantity: 0,
        unit: "PCS",
        inspectionStatus: "accepted",
        warehouseId: "wh-001",
        locationId: "loc-002",
      },
      {
        id: "grn-001-item-3",
        poItemId: "po-001-item-3",
        materialId: "mat-007",
        materialCode: "ACC-RVT-CU",
        materialName: "Copper Rivets",
        receivedQuantity: 20000,
        acceptedQuantity: 20000,
        rejectedQuantity: 0,
        unit: "PCS",
        inspectionStatus: "accepted",
        warehouseId: "wh-001",
        locationId: "loc-002",
      },
    ],
  },
  {
    id: "grn-002",
    grnNumber: "GRN-2026-0091",
    poId: "po-004",
    poNumber: "PO-2026-0314",
    supplierId: "sup-004",
    supplierName: "Precision Label & Packaging",
    receivedDate: "2026-08-15",
    receivedBy: "Sunita Yadav",
    notes: "300 pcs rejected — print misalignment on the woven label edge.",
    items: [
      {
        id: "grn-002-item-1",
        poItemId: "po-004-item-1",
        materialId: "mat-009",
        materialCode: "RAW-LBL-WV",
        materialName: "Woven Brand Labels",
        receivedQuantity: 12300,
        acceptedQuantity: 12000,
        rejectedQuantity: 300,
        unit: "PCS",
        inspectionStatus: "partially_accepted",
        warehouseId: "wh-001",
        locationId: "loc-002",
      },
    ],
  },
];
