import type { InventoryItem, StockMovement } from "@/types";

export const mockInventoryItems: InventoryItem[] = [
  {
    id: "inv-001",
    sku: "FAB-DBL-11",
    name: "Denim Blue 11 OZ",
    category: "fabric",
    unit: "meters",
    quantityInStock: 8400,
    reorderLevel: 3000,
    stockLevel: "healthy",
    warehouseLocation: "Fabric Store A-1",
    lastMovementDate: "2026-08-18",
    unitCost: 350,
  },
  {
    id: "inv-002",
    sku: "FAB-DBK-125",
    name: "Denim Black 12.5 OZ",
    category: "fabric",
    unit: "meters",
    quantityInStock: 1240,
    reorderLevel: 2500,
    stockLevel: "low",
    warehouseLocation: "Fabric Store A-2",
    lastMovementDate: "2026-08-17",
    unitCost: 380,
  },
  {
    id: "inv-003",
    sku: "FAB-STR-95",
    name: "Stretch Denim 9.5 OZ",
    category: "fabric",
    unit: "meters",
    quantityInStock: 5100,
    reorderLevel: 2000,
    stockLevel: "healthy",
    warehouseLocation: "Fabric Store A-1",
    lastMovementDate: "2026-08-18",
    unitCost: 410,
  },
  {
    id: "inv-004",
    sku: "FAB-GRY-10",
    name: "Denim Grey 10 OZ",
    category: "fabric",
    unit: "meters",
    quantityInStock: 380,
    reorderLevel: 2000,
    stockLevel: "critical",
    warehouseLocation: "Fabric Store A-3",
    lastMovementDate: "2026-08-15",
    unitCost: 365,
  },
  {
    id: "inv-005",
    sku: "FAB-IND-13",
    name: "Denim Indigo Rigid 13 OZ",
    category: "fabric",
    unit: "meters",
    quantityInStock: 0,
    reorderLevel: 1500,
    stockLevel: "out_of_stock",
    warehouseLocation: "Fabric Store A-3",
    lastMovementDate: "2026-08-10",
    unitCost: 480,
  },
  {
    id: "inv-006",
    sku: "ACC-ZIP-YKK",
    name: "YKK Zipper 5.5in",
    category: "accessory",
    unit: "pcs",
    quantityInStock: 42000,
    reorderLevel: 15000,
    stockLevel: "healthy",
    warehouseLocation: "Trims Store B-1",
    lastMovementDate: "2026-08-19",
    unitCost: 14,
  },
  {
    id: "inv-007",
    sku: "ACC-BTN-JN",
    name: "Jean Button 17mm",
    category: "accessory",
    unit: "pcs",
    quantityInStock: 6200,
    reorderLevel: 8000,
    stockLevel: "low",
    warehouseLocation: "Trims Store B-1",
    lastMovementDate: "2026-08-16",
    unitCost: 5,
  },
  {
    id: "inv-008",
    sku: "ACC-RVT-CU",
    name: "Copper Rivets",
    category: "accessory",
    unit: "pcs",
    quantityInStock: 28500,
    reorderLevel: 10000,
    stockLevel: "healthy",
    warehouseLocation: "Trims Store B-2",
    lastMovementDate: "2026-08-18",
    unitCost: 2,
  },
  {
    id: "inv-009",
    sku: "RAW-THR-POL",
    name: "Polyester Thread Cone",
    category: "raw_material",
    unit: "cones",
    quantityInStock: 940,
    reorderLevel: 400,
    stockLevel: "healthy",
    warehouseLocation: "Trims Store B-3",
    lastMovementDate: "2026-08-17",
    unitCost: 110,
  },
  {
    id: "inv-010",
    sku: "RAW-LBL-WV",
    name: "Woven Brand Labels",
    category: "raw_material",
    unit: "pcs",
    quantityInStock: 1100,
    reorderLevel: 5000,
    stockLevel: "critical",
    warehouseLocation: "Trims Store B-3",
    lastMovementDate: "2026-08-12",
    unitCost: 4,
  },
  {
    id: "inv-011",
    sku: "FG-STR118-BLK-32",
    name: "Straight Fit STR-118 Black W32",
    category: "finished_good",
    unit: "pcs",
    quantityInStock: 640,
    reorderLevel: 0,
    stockLevel: "healthy",
    warehouseLocation: "FG Warehouse C-1",
    lastMovementDate: "2026-08-19",
    unitCost: 1150,
  },
  {
    id: "inv-012",
    sku: "FG-SKN440-BLU-30",
    name: "Skinny Fit SKN-440 Blue W30",
    category: "finished_good",
    unit: "pcs",
    quantityInStock: 210,
    reorderLevel: 0,
    stockLevel: "healthy",
    warehouseLocation: "FG Warehouse C-1",
    lastMovementDate: "2026-08-18",
    unitCost: 1090,
  },
];

export const mockStockMovements: StockMovement[] = [
  {
    id: "mov-001",
    itemId: "inv-001",
    itemName: "Denim Blue 11 OZ",
    type: "issue",
    quantity: 1200,
    unit: "meters",
    reference: "ORD-2026-00452 · Cutting",
    date: "2026-08-18",
    performedBy: "Deepak Patil",
  },
  {
    id: "mov-002",
    itemId: "inv-006",
    itemName: "YKK Zipper 5.5in",
    type: "receipt",
    quantity: 20000,
    unit: "pcs",
    reference: "GRN-2026-0311 · Metro Trims Supply",
    date: "2026-08-19",
    performedBy: "Anjali Mehta",
  },
  {
    id: "mov-003",
    itemId: "inv-004",
    itemName: "Denim Grey 10 OZ",
    type: "issue",
    quantity: 950,
    unit: "meters",
    reference: "ORD-2026-00457 · Cutting",
    date: "2026-08-15",
    performedBy: "Deepak Patil",
  },
  {
    id: "mov-004",
    itemId: "inv-010",
    itemName: "Woven Brand Labels",
    type: "adjustment",
    quantity: -300,
    unit: "pcs",
    reference: "Stock count correction",
    date: "2026-08-12",
    performedBy: "Anjali Mehta",
  },
  {
    id: "mov-005",
    itemId: "inv-011",
    itemName: "Straight Fit STR-118 Black W32",
    type: "transfer",
    quantity: 640,
    unit: "pcs",
    reference: "Finishing → FG Warehouse C-1",
    date: "2026-08-19",
    performedBy: "Ravi Chandran",
  },
];
