import type { Material } from "@/types";

export const mockMaterials: Material[] = [
  {
    id: "mat-001",
    code: "FAB-DBL-11",
    name: "Denim Blue 11 OZ",
    materialGroupId: "mg-001",
    uomId: "uom-003",
    supplierId: "sup-002",
    colorId: "color-001",
    description: "Ring-spun indigo denim for core 5-pocket styles.",
    fabricDetails: { composition: "98% Cotton, 2% Elastane", weightOz: 11, widthCm: 150, stretch: true },
    status: "active",
  },
  {
    id: "mat-002",
    code: "FAB-GRY-10",
    name: "Denim Grey 10 OZ",
    materialGroupId: "mg-001",
    uomId: "uom-003",
    supplierId: "sup-002",
    colorId: "color-005",
    description: "Rigid grey denim.",
    fabricDetails: { composition: "100% Cotton", weightOz: 10, widthCm: 150, stretch: false },
    status: "active",
  },
  {
    id: "mat-003",
    code: "FAB-STR-95",
    name: "Stretch Denim 9.5 OZ",
    materialGroupId: "mg-002",
    uomId: "uom-003",
    supplierId: "sup-003",
    colorId: "color-003",
    description: "Lightweight stretch denim for slim and skinny fits.",
    fabricDetails: { composition: "97% Cotton, 3% Elastane", weightOz: 9.5, widthCm: 152, stretch: true },
    status: "active",
  },
  {
    id: "mat-004",
    code: "FAB-IND-13",
    name: "Denim Indigo Rigid 13 OZ",
    materialGroupId: "mg-001",
    uomId: "uom-003",
    supplierId: "sup-002",
    colorId: "color-001",
    description: "Heavyweight rigid indigo denim.",
    fabricDetails: { composition: "100% Cotton", weightOz: 13, widthCm: 150, stretch: false },
    status: "active",
  },
  {
    id: "mat-005",
    code: "ACC-ZIP-YKK",
    name: "YKK Zipper 5.5in",
    materialGroupId: "mg-004",
    uomId: "uom-001",
    supplierId: "sup-001",
    description: "YKK metal zipper, antique brass finish.",
    status: "active",
  },
  {
    id: "mat-006",
    code: "ACC-BTN-JN",
    name: "Jean Button 17mm",
    materialGroupId: "mg-003",
    uomId: "uom-001",
    supplierId: "sup-001",
    description: "Tack button, antique brass.",
    status: "active",
  },
  {
    id: "mat-007",
    code: "ACC-RVT-CU",
    name: "Copper Rivets",
    materialGroupId: "mg-003",
    uomId: "uom-001",
    supplierId: "sup-001",
    description: "Pocket reinforcement rivets.",
    status: "active",
  },
  {
    id: "mat-008",
    code: "RAW-THR-POL",
    name: "Polyester Thread Cone",
    materialGroupId: "mg-005",
    uomId: "uom-002",
    supplierId: "sup-001",
    description: "Core-spun polyester sewing thread.",
    status: "active",
  },
  {
    id: "mat-009",
    code: "RAW-LBL-WV",
    name: "Woven Brand Labels",
    materialGroupId: "mg-006",
    uomId: "uom-001",
    supplierId: "sup-004",
    description: "Main woven brand label, sewn into back waistband.",
    status: "active",
  },
  {
    id: "mat-010",
    code: "PACK-BAG-PL",
    name: "Poly Bag 12x16",
    materialGroupId: "mg-007",
    uomId: "uom-001",
    supplierId: "sup-004",
    description: "Individual garment poly bag.",
    status: "active",
  },
  {
    id: "mat-011",
    code: "PACK-CTN-01",
    name: "Export Carton Box",
    materialGroupId: "mg-007",
    uomId: "uom-006",
    supplierId: "sup-004",
    description: "5-ply export carton, 60x40x40cm.",
    status: "inactive",
  },
];
