import type { Order } from "@/types";

export const mockOrders: Order[] = [
  {
    id: "ord-001",
    orderNumber: "ORD-2026-00452",
    customerId: "cust-001",
    customerName: "Urban Denim Co.",
    styleCode: "SLIM-502",
    styleName: "Slim Fit Jean",
    fabric: "Denim Blue 11 OZ",
    quantity: 5000,
    quantityProduced: 3850,
    status: "in_production",
    orderDate: "2026-06-12",
    dueDate: "2026-08-28",
    isDelayed: false,
    currentStage: "washing",
    priority: "high",
  },
  {
    id: "ord-002",
    orderNumber: "ORD-2026-00453",
    customerId: "cust-003",
    customerName: "Northline Trading",
    styleCode: "STR-118",
    styleName: "Straight Fit Jean",
    fabric: "Denim Black 12.5 OZ",
    quantity: 8000,
    quantityProduced: 8000,
    status: "completed",
    orderDate: "2026-05-20",
    dueDate: "2026-07-30",
    isDelayed: false,
    currentStage: "dispatch",
    priority: "normal",
  },
  {
    id: "ord-003",
    orderNumber: "ORD-2026-00454",
    customerId: "cust-002",
    customerName: "Bluewash Apparel",
    styleCode: "TAP-330",
    styleName: "Tapered Jean",
    fabric: "Stretch Denim 9.5 OZ",
    quantity: 3200,
    quantityProduced: 1180,
    status: "delayed",
    orderDate: "2026-06-25",
    dueDate: "2026-08-10",
    isDelayed: true,
    currentStage: "sewing",
    priority: "high",
  },
  {
    id: "ord-004",
    orderNumber: "ORD-2026-00455",
    customerId: "cust-004",
    customerName: "Studio Fit Co.",
    styleCode: "SKN-440",
    styleName: "Skinny Fit Jean",
    fabric: "Stretch Denim 9.5 OZ",
    quantity: 2400,
    quantityProduced: 2400,
    status: "dispatched",
    orderDate: "2026-05-02",
    dueDate: "2026-07-05",
    isDelayed: false,
    currentStage: "dispatch",
    priority: "normal",
  },
  {
    id: "ord-005",
    orderNumber: "ORD-2026-00456",
    customerId: "cust-005",
    customerName: "Westgate Garments",
    styleCode: "BOOT-210",
    styleName: "Bootcut Jean",
    fabric: "Denim Indigo Rigid 13 OZ",
    quantity: 4500,
    quantityProduced: 620,
    status: "in_production",
    orderDate: "2026-07-01",
    dueDate: "2026-09-15",
    isDelayed: false,
    currentStage: "cutting",
    priority: "normal",
  },
  {
    id: "ord-006",
    orderNumber: "ORD-2026-00457",
    customerId: "cust-003",
    customerName: "Northline Trading",
    styleCode: "RLX-075",
    styleName: "Relaxed Fit Jean",
    fabric: "Denim Grey 10 OZ",
    quantity: 6000,
    quantityProduced: 4980,
    status: "in_production",
    orderDate: "2026-06-18",
    dueDate: "2026-08-22",
    isDelayed: false,
    currentStage: "finishing",
    priority: "normal",
  },
  {
    id: "ord-007",
    orderNumber: "ORD-2026-00458",
    customerId: "cust-006",
    customerName: "Meridian Clothing",
    styleCode: "SLIM-502",
    styleName: "Slim Fit Jean",
    fabric: "Denim Blue 11 OZ",
    quantity: 1800,
    quantityProduced: 340,
    status: "delayed",
    orderDate: "2026-06-30",
    dueDate: "2026-08-05",
    isDelayed: true,
    currentStage: "cutting",
    priority: "high",
  },
  {
    id: "ord-008",
    orderNumber: "ORD-2026-00459",
    customerId: "cust-001",
    customerName: "Urban Denim Co.",
    styleCode: "STR-118",
    styleName: "Straight Fit Jean",
    fabric: "Denim Black 12.5 OZ",
    quantity: 3600,
    quantityProduced: 3600,
    status: "in_production",
    orderDate: "2026-06-05",
    dueDate: "2026-08-18",
    isDelayed: false,
    currentStage: "qc",
    priority: "normal",
  },
  {
    id: "ord-009",
    orderNumber: "ORD-2026-00460",
    customerId: "cust-002",
    customerName: "Bluewash Apparel",
    styleCode: "TAP-330",
    styleName: "Tapered Jean",
    fabric: "Denim Grey 10 OZ",
    quantity: 2000,
    quantityProduced: 0,
    status: "confirmed",
    orderDate: "2026-08-05",
    dueDate: "2026-10-01",
    isDelayed: false,
    currentStage: "cutting",
    priority: "low",
  },
  {
    id: "ord-010",
    orderNumber: "ORD-2026-00461",
    customerId: "cust-005",
    customerName: "Westgate Garments",
    styleCode: "SKN-440",
    styleName: "Skinny Fit Jean",
    fabric: "Stretch Denim 9.5 OZ",
    quantity: 5200,
    quantityProduced: 5200,
    status: "in_production",
    orderDate: "2026-05-28",
    dueDate: "2026-08-01",
    isDelayed: false,
    currentStage: "packing",
    priority: "normal",
  },
  {
    id: "ord-011",
    orderNumber: "ORD-2026-00462",
    customerId: "cust-004",
    customerName: "Studio Fit Co.",
    styleCode: "RLX-075",
    styleName: "Relaxed Fit Jean",
    fabric: "Denim Indigo Rigid 13 OZ",
    quantity: 1500,
    quantityProduced: 0,
    status: "draft",
    orderDate: "2026-08-15",
    dueDate: "2026-10-20",
    isDelayed: false,
    currentStage: "cutting",
    priority: "low",
  },
  {
    id: "ord-012",
    orderNumber: "ORD-2026-00463",
    customerId: "cust-003",
    customerName: "Northline Trading",
    styleCode: "BOOT-210",
    styleName: "Bootcut Jean",
    fabric: "Denim Blue 11 OZ",
    quantity: 3000,
    quantityProduced: 2650,
    status: "in_production",
    orderDate: "2026-06-22",
    dueDate: "2026-08-20",
    isDelayed: false,
    currentStage: "washing",
    priority: "normal",
  },
];

export const orderStatusLabels: Record<Order["status"], string> = {
  draft: "Draft",
  confirmed: "Confirmed",
  in_production: "In Production",
  delayed: "Delayed",
  completed: "Completed",
  dispatched: "Dispatched",
  cancelled: "Cancelled",
};
