import type { PurchaseOrder, PurchaseRequest, Supplier } from "@/types";

export const mockSuppliers: Supplier[] = [
  {
    id: "sup-001",
    name: "Metro Trims Supply",
    category: "accessory",
    location: "Ahmedabad, India",
    rating: 4.6,
    activeOrders: 3,
    onTimeDeliveryRate: 96,
  },
  {
    id: "sup-002",
    name: "Vardhman Denim Mills",
    category: "fabric",
    location: "Ludhiana, India",
    rating: 4.8,
    activeOrders: 2,
    onTimeDeliveryRate: 92,
  },
  {
    id: "sup-003",
    name: "Sunrise Textile Exports",
    category: "fabric",
    location: "Surat, India",
    rating: 4.1,
    activeOrders: 1,
    onTimeDeliveryRate: 84,
  },
  {
    id: "sup-004",
    name: "Precision Label & Packaging",
    category: "raw_material",
    location: "Bengaluru, India",
    rating: 4.4,
    activeOrders: 1,
    onTimeDeliveryRate: 90,
  },
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: "po-001",
    poNumber: "PO-2026-0311",
    supplierId: "sup-001",
    supplierName: "Metro Trims Supply",
    itemSummary: "YKK Zippers, Jean Buttons, Copper Rivets",
    totalValue: 705000,
    status: "received",
    orderDate: "2026-08-05",
    expectedDate: "2026-08-19",
  },
  {
    id: "po-002",
    poNumber: "PO-2026-0312",
    supplierId: "sup-002",
    supplierName: "Vardhman Denim Mills",
    itemSummary: "Denim Grey 10 OZ — 5,000 meters",
    totalValue: 1825000,
    status: "sent",
    orderDate: "2026-08-14",
    expectedDate: "2026-08-27",
  },
  {
    id: "po-003",
    poNumber: "PO-2026-0313",
    supplierId: "sup-002",
    supplierName: "Vardhman Denim Mills",
    itemSummary: "Denim Indigo Rigid 13 OZ — 3,000 meters",
    totalValue: 1440000,
    status: "sent",
    orderDate: "2026-08-16",
    expectedDate: "2026-08-30",
  },
  {
    id: "po-004",
    poNumber: "PO-2026-0314",
    supplierId: "sup-004",
    supplierName: "Precision Label & Packaging",
    itemSummary: "Woven Brand Labels — 20,000 pcs",
    totalValue: 80000,
    status: "partially_received",
    orderDate: "2026-08-10",
    expectedDate: "2026-08-20",
  },
  {
    id: "po-005",
    poNumber: "PO-2026-0315",
    supplierId: "sup-003",
    supplierName: "Sunrise Textile Exports",
    itemSummary: "Stretch Denim 9.5 OZ — 4,000 meters",
    totalValue: 1640000,
    status: "draft",
    orderDate: "2026-08-19",
    expectedDate: "2026-09-05",
  },
];

export const mockPurchaseRequests: PurchaseRequest[] = [
  {
    id: "pr-001",
    requestNumber: "PR-2026-0522",
    requestedBy: "Deepak Patil",
    itemSummary: "Denim Grey 10 OZ",
    quantity: 5000,
    unit: "meters",
    neededBy: "2026-08-25",
    status: "approved",
    urgency: "high",
  },
  {
    id: "pr-002",
    requestNumber: "PR-2026-0523",
    requestedBy: "Anjali Mehta",
    itemSummary: "Woven Brand Labels",
    quantity: 20000,
    unit: "pcs",
    neededBy: "2026-08-22",
    status: "pending_approval",
    urgency: "high",
  },
  {
    id: "pr-003",
    requestNumber: "PR-2026-0524",
    requestedBy: "Priya Kulkarni",
    itemSummary: "Jean Button 17mm",
    quantity: 15000,
    unit: "pcs",
    neededBy: "2026-08-28",
    status: "pending_approval",
    urgency: "normal",
  },
  {
    id: "pr-004",
    requestNumber: "PR-2026-0525",
    requestedBy: "Rakesh Verma",
    itemSummary: "Denim Indigo Rigid 13 OZ",
    quantity: 3000,
    unit: "meters",
    neededBy: "2026-09-01",
    status: "approved",
    urgency: "normal",
  },
];
