import type { PurchaseOrder, PurchaseRequest, Supplier } from "@/types";

export const mockSuppliers: Supplier[] = [
  {
    id: "sup-001",
    code: "SUP-001",
    name: "Metro Trims Supply",
    type: "accessories",
    category: "accessory",
    location: "Ahmedabad, India",
    address: "Naroda Industrial Estate, Ahmedabad",
    contactPerson: "Rohit Sharma",
    email: "rohit@metrotrims.in",
    phone: "+91 79 4012 5566",
    status: "active",
    notes: "",
    rating: 4.6,
    activeOrders: 3,
    onTimeDeliveryRate: 96,
  },
  {
    id: "sup-002",
    code: "SUP-002",
    name: "Vardhman Denim Mills",
    type: "fabric",
    category: "fabric",
    location: "Ludhiana, India",
    address: "Focal Point, Ludhiana",
    contactPerson: "Gurpreet Singh",
    email: "gurpreet@vardhmandenim.in",
    phone: "+91 161 500 3421",
    status: "active",
    notes: "Primary indigo denim supplier.",
    rating: 4.8,
    activeOrders: 2,
    onTimeDeliveryRate: 92,
  },
  {
    id: "sup-003",
    code: "SUP-003",
    name: "Sunrise Textile Exports",
    type: "fabric",
    category: "fabric",
    location: "Surat, India",
    address: "Pandesara Industrial Area, Surat",
    contactPerson: "Kavita Rao",
    email: "kavita@sunrisetextile.in",
    phone: "+91 261 400 7788",
    status: "active",
    notes: "",
    rating: 4.1,
    activeOrders: 1,
    onTimeDeliveryRate: 84,
  },
  {
    id: "sup-004",
    code: "SUP-004",
    name: "Precision Label & Packaging",
    type: "packaging",
    category: "raw_material",
    location: "Bengaluru, India",
    address: "Peenya Industrial Area, Bengaluru",
    contactPerson: "Arvind Menon",
    email: "arvind@precisionlabel.in",
    phone: "+91 80 4123 9900",
    status: "active",
    notes: "",
    rating: 4.4,
    activeOrders: 1,
    onTimeDeliveryRate: 90,
  },
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: "po-001",
    poNumber: "PO-2026-0311",
    supplierId: "sup-001",
    supplierName: "Metro Trims Supply",
    orderDate: "2026-08-05",
    expectedDate: "2026-08-19",
    status: "received",
    items: [
      { id: "po-001-item-1", materialId: "mat-005", materialCode: "ACC-ZIP-YKK", materialName: "YKK Zipper 5.5in", quantity: 10000, unit: "PCS", unitPrice: 8, receivedQuantity: 10000 },
      { id: "po-001-item-2", materialId: "mat-006", materialCode: "ACC-BTN-JN", materialName: "Jean Button 17mm", quantity: 15000, unit: "PCS", unitPrice: 3, receivedQuantity: 15000 },
      { id: "po-001-item-3", materialId: "mat-007", materialCode: "ACC-RVT-CU", materialName: "Copper Rivets", quantity: 20000, unit: "PCS", unitPrice: 2, receivedQuantity: 20000 },
    ],
    subtotal: 165000,
    discount: 0,
    tax: 8250,
    totalValue: 173250,
  },
  {
    id: "po-002",
    poNumber: "PO-2026-0312",
    supplierId: "sup-002",
    supplierName: "Vardhman Denim Mills",
    orderDate: "2026-08-14",
    expectedDate: "2026-08-27",
    status: "sent",
    items: [
      { id: "po-002-item-1", materialId: "mat-002", materialCode: "FAB-GRY-10", materialName: "Denim Grey 10 OZ", quantity: 5000, unit: "MTR", unitPrice: 320, receivedQuantity: 0 },
    ],
    subtotal: 1600000,
    discount: 0,
    tax: 0,
    totalValue: 1600000,
  },
  {
    id: "po-003",
    poNumber: "PO-2026-0313",
    supplierId: "sup-002",
    supplierName: "Vardhman Denim Mills",
    orderDate: "2026-08-16",
    expectedDate: "2026-08-30",
    status: "sent",
    items: [
      { id: "po-003-item-1", materialId: "mat-004", materialCode: "FAB-IND-13", materialName: "Denim Indigo Rigid 13 OZ", quantity: 3000, unit: "MTR", unitPrice: 400, receivedQuantity: 0 },
    ],
    subtotal: 1200000,
    discount: 0,
    tax: 0,
    totalValue: 1200000,
  },
  {
    id: "po-004",
    poNumber: "PO-2026-0314",
    supplierId: "sup-004",
    supplierName: "Precision Label & Packaging",
    orderDate: "2026-08-10",
    expectedDate: "2026-08-20",
    status: "partially_received",
    items: [
      { id: "po-004-item-1", materialId: "mat-009", materialCode: "RAW-LBL-WV", materialName: "Woven Brand Labels", quantity: 20000, unit: "PCS", unitPrice: 4, receivedQuantity: 12000 },
    ],
    subtotal: 80000,
    discount: 0,
    tax: 0,
    totalValue: 80000,
  },
  {
    id: "po-005",
    poNumber: "PO-2026-0315",
    supplierId: "sup-003",
    supplierName: "Sunrise Textile Exports",
    orderDate: "2026-08-19",
    expectedDate: "2026-09-05",
    status: "draft",
    items: [
      { id: "po-005-item-1", materialId: "mat-003", materialCode: "FAB-STR-95", materialName: "Stretch Denim 9.5 OZ", quantity: 4000, unit: "MTR", unitPrice: 410, receivedQuantity: 0 },
    ],
    subtotal: 1640000,
    discount: 0,
    tax: 0,
    totalValue: 1640000,
  },
  {
    id: "po-006",
    poNumber: "PO-2026-0316",
    supplierId: "sup-001",
    supplierName: "Metro Trims Supply",
    orderDate: "2026-08-18",
    expectedDate: "2026-09-02",
    status: "pending_approval",
    items: [
      { id: "po-006-item-1", materialId: "mat-008", materialCode: "RAW-THR-POL", materialName: "Polyester Thread Cone", quantity: 200, unit: "KG", unitPrice: 550, receivedQuantity: 0 },
    ],
    subtotal: 110000,
    discount: 0,
    tax: 0,
    totalValue: 110000,
  },
  {
    id: "po-007",
    poNumber: "PO-2026-0317",
    supplierId: "sup-004",
    supplierName: "Precision Label & Packaging",
    orderDate: "2026-07-28",
    expectedDate: "2026-08-10",
    status: "cancelled",
    items: [
      { id: "po-007-item-1", materialId: "mat-010", materialCode: "PACK-BAG-PL", materialName: "Poly Bag 12x16", quantity: 50000, unit: "PCS", unitPrice: 1.5, receivedQuantity: 0 },
    ],
    subtotal: 75000,
    discount: 0,
    tax: 0,
    totalValue: 75000,
    notes: "Cancelled — sufficient stock already on hand.",
  },
  {
    id: "po-008",
    poNumber: "PO-2026-0318",
    supplierId: "sup-001",
    supplierName: "Metro Trims Supply",
    orderDate: "2026-08-17",
    expectedDate: "2026-08-29",
    status: "approved",
    items: [
      { id: "po-008-item-1", materialId: "mat-005", materialCode: "ACC-ZIP-YKK", materialName: "YKK Zipper 5.5in", quantity: 5000, unit: "PCS", unitPrice: 8, receivedQuantity: 0 },
      { id: "po-008-item-2", materialId: "mat-007", materialCode: "ACC-RVT-CU", materialName: "Copper Rivets", quantity: 8000, unit: "PCS", unitPrice: 2, receivedQuantity: 0 },
    ],
    subtotal: 56000,
    discount: 0,
    tax: 0,
    totalValue: 56000,
  },
  {
    id: "po-009",
    poNumber: "PO-2026-0319",
    supplierId: "sup-002",
    supplierName: "Vardhman Denim Mills",
    orderDate: "2026-08-12",
    expectedDate: "2026-08-24",
    status: "sent",
    items: [
      { id: "po-009-item-1", materialId: "mat-001", materialCode: "FAB-DBL-11", materialName: "Denim Blue 11 OZ", quantity: 1000, unit: "MTR", unitPrice: 350, receivedQuantity: 0 },
    ],
    subtotal: 350000,
    discount: 0,
    tax: 0,
    totalValue: 350000,
  },
];

export const mockPurchaseRequests: PurchaseRequest[] = [
  {
    id: "pr-001",
    requestNumber: "PR-2026-0522",
    requestedBy: "Deepak Patil",
    materialId: "mat-002",
    materialCode: "FAB-GRY-10",
    materialName: "Denim Grey 10 OZ",
    quantity: 5000,
    unit: "MTR",
    requiredDate: "2026-08-25",
    requestDate: "2026-08-11",
    preferredSupplierId: "sup-002",
    priority: "high",
    reason: "Production requirement — upcoming order",
    status: "converted",
    convertedToPoId: "po-002",
  },
  {
    id: "pr-002",
    requestNumber: "PR-2026-0523",
    requestedBy: "Anjali Mehta",
    materialId: "mat-009",
    materialCode: "RAW-LBL-WV",
    materialName: "Woven Brand Labels",
    quantity: 20000,
    unit: "PCS",
    requiredDate: "2026-08-22",
    requestDate: "2026-08-08",
    preferredSupplierId: "sup-004",
    priority: "high",
    reason: "Production requirement — label stock exhausted",
    status: "converted",
    convertedToPoId: "po-004",
  },
  {
    id: "pr-003",
    requestNumber: "PR-2026-0524",
    requestedBy: "Priya Kulkarni",
    materialId: "mat-006",
    materialCode: "ACC-BTN-JN",
    materialName: "Jean Button 17mm",
    quantity: 15000,
    unit: "PCS",
    requiredDate: "2026-08-28",
    requestDate: "2026-08-14",
    preferredSupplierId: "sup-001",
    priority: "normal",
    reason: "Low stock replenishment",
    status: "pending_approval",
  },
  {
    id: "pr-004",
    requestNumber: "PR-2026-0525",
    requestedBy: "Rakesh Verma",
    materialId: "mat-004",
    materialCode: "FAB-IND-13",
    materialName: "Denim Indigo Rigid 13 OZ",
    quantity: 3000,
    unit: "MTR",
    requiredDate: "2026-09-01",
    requestDate: "2026-08-15",
    preferredSupplierId: "sup-002",
    priority: "urgent",
    reason: "Material is out of stock",
    status: "approved",
  },
  {
    id: "pr-005",
    requestNumber: "PR-2026-0526",
    requestedBy: "Meena Iyer",
    materialId: "mat-003",
    materialCode: "FAB-STR-95",
    materialName: "Stretch Denim 9.5 OZ",
    quantity: 2000,
    unit: "MTR",
    requiredDate: "2026-09-10",
    requestDate: "2026-08-19",
    preferredSupplierId: "sup-003",
    priority: "normal",
    reason: "Upcoming order requirement",
    status: "draft",
  },
  {
    id: "pr-006",
    requestNumber: "PR-2026-0527",
    requestedBy: "Arjun Nair",
    materialId: "mat-007",
    materialCode: "ACC-RVT-CU",
    materialName: "Copper Rivets",
    quantity: 5000,
    unit: "PCS",
    requiredDate: "2026-08-20",
    requestDate: "2026-08-05",
    preferredSupplierId: "sup-001",
    priority: "low",
    reason: "Buffer stock",
    notes: "Rejected — sufficient stock already available.",
    status: "rejected",
  },
  {
    id: "pr-007",
    requestNumber: "PR-2026-0528",
    requestedBy: "Kiran Desai",
    materialId: "mat-008",
    materialCode: "RAW-THR-POL",
    materialName: "Polyester Thread Cone",
    quantity: 100,
    unit: "KG",
    requiredDate: "2026-08-30",
    requestDate: "2026-08-18",
    preferredSupplierId: "sup-001",
    priority: "normal",
    reason: "Low stock replenishment",
    status: "submitted",
  },
];
