import type { Style } from "@/types";

const coreOps = ["proc-001", "proc-002", "proc-003", "proc-004", "proc-006", "proc-007"];
const opsWithIron = [...coreOps.slice(0, 4), "proc-005", ...coreOps.slice(4)];

export const mockStyles: Style[] = [
  {
    id: "style-001",
    styleCode: "SLIM-502",
    name: "Slim 502",
    productId: "prod-001",
    category: "Men's Denim",
    gender: "men",
    fit: "Slim",
    fabricType: "Stretch Denim 9.5 OZ",
    defaultOperationIds: opsWithIron,
    status: "active",
  },
  {
    id: "style-002",
    styleCode: "STR-118",
    name: "Straight 118",
    productId: "prod-002",
    category: "Men's Denim",
    gender: "men",
    fit: "Straight",
    fabricType: "Denim Grey 10 OZ",
    defaultOperationIds: coreOps,
    status: "active",
  },
  {
    id: "style-003",
    styleCode: "TAP-330",
    name: "Tapered 330",
    productId: "prod-003",
    category: "Men's Denim",
    gender: "men",
    fit: "Tapered",
    fabricType: "Denim Indigo Rigid 13 OZ",
    defaultOperationIds: opsWithIron,
    status: "active",
  },
  {
    id: "style-004",
    styleCode: "SKN-440",
    name: "Skinny 440",
    productId: "prod-004",
    category: "Men's Denim",
    gender: "men",
    fit: "Skinny",
    fabricType: "Stretch Denim 9.5 OZ",
    defaultOperationIds: coreOps,
    status: "active",
  },
  {
    id: "style-005",
    styleCode: "BOOT-210",
    name: "Bootcut 210",
    productId: "prod-005",
    category: "Men's Denim",
    gender: "men",
    fit: "Bootcut",
    fabricType: "Denim Blue 11 OZ",
    defaultOperationIds: coreOps,
    status: "active",
  },
  {
    id: "style-006",
    styleCode: "RLX-075",
    name: "Relaxed 075",
    productId: "prod-006",
    category: "Men's Denim",
    gender: "men",
    fit: "Relaxed",
    fabricType: "Denim Grey 10 OZ",
    defaultOperationIds: coreOps,
    status: "active",
  },
];
